apiVersion: v1
entries:
  firecrest-api:
  - apiVersion: v2
    appVersion: 2.4.2
    created: "2025-12-16T14:41:29.586958586Z"
    description: A Kubernetes Helm chart for FirecREST API
    digest: 949d392a4122bc3d434f4c97bb7f7b9ca6404769e97321464680c8212e6f0166
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.4.2.tgz
    version: 2.4.2
  - apiVersion: v2
    appVersion: 2.4.1
    created: "2025-12-16T14:41:29.586178953Z"
    description: A Kubernetes Helm chart for FirecREST API
    digest: 1e9523c7bb0861bc451c8315bb4b9b1190191a91e8307ec2b25cd311a6ca0fb0
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.4.1.tgz
    version: 2.4.1
  - apiVersion: v2
    appVersion: 2.4.0
    created: "2025-12-16T14:41:29.5857102Z"
    description: A Kubernetes Helm chart for FirecREST API
    digest: 0d049fd92c2aff4e5707f866a85ce2e61cabcbb3b474475811460ae17d49c9ff
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.4.0.tgz
    version: 2.4.0
  - apiVersion: v2
    appVersion: 2.3.1
    created: "2025-12-16T14:41:29.585178239Z"
    description: FirecREST APIs (version 2)
    digest: 7d84c53745eebdbd2df2dccb45867850b3a12c33443bbdd5d2cef74689bf75eb
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.3.1.tgz
    version: 2.3.1
  - apiVersion: v2
    appVersion: 2.3.0
    created: "2025-12-16T14:41:29.585084845Z"
    description: FirecREST APIs (version 2)
    digest: 16aa3782a6ee5b5491f334d064f8624724cba0d81b5e5bf0282d3930b0a0851c
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v2
    appVersion: 2.2.9
    created: "2025-12-16T14:41:29.58499118Z"
    description: FirecREST APIs (version 2)
    digest: 4a0b1ca4bab1cedf97464fd8fcef6ac845270fde5fca9960cfd7fe3a94af16e0
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.2.9.tgz
    version: 2.2.9
  - apiVersion: v2
    appVersion: 2.2.8
    created: "2025-12-16T14:41:29.584847543Z"
    description: FirecREST APIs (version 2)
    digest: 09eb7664b3c58f283a2b2f436c944727d728ffe2b2cfdaec4750ddfa4b393de2
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.2.8.tgz
    version: 2.2.8
  - apiVersion: v2
    appVersion: 2.2.7
    created: "2025-12-16T14:41:29.584751684Z"
    description: FirecREST APIs (version 2)
    digest: 06148b3d5e425917c24d18bb7a5c49f4b4d8b24dda16344e3e4271477fe4deb9
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.2.7.tgz
    version: 2.2.7
  - apiVersion: v2
    appVersion: 2.2.6
    created: "2025-12-16T14:41:29.584652689Z"
    description: FirecREST APIs (version 2)
    digest: 3e6e252a9f1925ffefb327d0cf52109095cf9abd392f4064bc836957086ea947
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.2.6.tgz
    version: 2.2.6
  - apiVersion: v2
    appVersion: 2.2.5
    created: "2025-12-16T14:41:29.584532696Z"
    description: FirecREST APIs (version 2)
    digest: 1b4ff150c108e8615dae06e0919c8c46b8b0942f790a735f2b380e80060b160d
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.2.5.tgz
    version: 2.2.5
  - apiVersion: v2
    appVersion: 2.2.4
    created: "2025-12-16T14:41:29.584430115Z"
    description: FirecREST APIs (version 2)
    digest: dbf02cfd9f2153576fc2a0ddadfb61694260f780e15f9a5770b1b10f8aeeef1b
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.2.4.tgz
    version: 2.2.4
  - apiVersion: v2
    appVersion: 2.2.3
    created: "2025-12-16T14:41:29.584312936Z"
    description: FirecREST APIs (version 2)
    digest: c931edf0c7a5e1b8c0b7524faf5bb0eccde6a29ca27b8a60508e97961205138c
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.2.3.tgz
    version: 2.2.3
  - apiVersion: v2
    appVersion: 2.2.2
    created: "2025-12-16T14:41:29.584212459Z"
    description: FirecREST APIs (version 2)
    digest: b39a0572a21642deae599395e40e245c24f9cf9226fccaf5decd566902adb6ab
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.2.2.tgz
    version: 2.2.2
  - apiVersion: v2
    appVersion: 2.2.1
    created: "2025-12-16T14:41:29.584115579Z"
    description: FirecREST APIs (version 2)
    digest: 9d8c78dea48561173c62a59b9a6a82dfc93428984aec2cba48e40bd1fecaa674
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.2.1.tgz
    version: 2.2.1
  - apiVersion: v2
    appVersion: 2.2.0
    created: "2025-12-16T14:41:29.584001155Z"
    description: FirecREST APIs (version 2)
    digest: ece5004a442b167965846e573659631acbb63dd0131ef122760fc7f923731110
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.2.0.tgz
    version: 2.2.0
  - apiVersion: v2
    appVersion: 2.1.5
    created: "2025-12-16T14:41:29.583902972Z"
    description: FirecREST APIs (version 2)
    digest: 172eb31affaac2e2053524a35d32a2eb94a815469d0af76d6c8cac10f1ddea41
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.1.5.tgz
    version: 2.1.5
  - apiVersion: v2
    appVersion: 2.1.4
    created: "2025-12-16T14:41:29.583785934Z"
    description: FirecREST APIs (version 2)
    digest: 62c98cce2cbe559f7fe1fd47bdeacd057da31e94986e63d186cca3e67e0f7b2d
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.1.4.tgz
    version: 2.1.4
  - apiVersion: v2
    appVersion: 2.1.3
    created: "2025-12-16T14:41:29.583686429Z"
    description: FirecREST APIs (version 2)
    digest: 5c19c477f9595cd5f27f879e1598a769e0104e86843a27f67c6741c31244008a
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.1.3.tgz
    version: 2.1.3
  - apiVersion: v2
    appVersion: 2.1.3-beta.13
    created: "2025-12-16T14:41:29.583528635Z"
    description: FirecREST APIs (version 2)
    digest: ccc377c0cd1e7b1e9dc0e5a31213f5c37db3902f675db9731e88c9ef51cf4908
    name: firecrest-api
    type: application
    urls:
    - https://eth-cscs.github.io/firecrest-v2/charts/firecrest-api-2.1.3-beta.13.tgz
    version: 2.1.3-beta.13
generated: "2025-12-16T14:41:29.583318774Z"
